name: CI
on:
  workflow_dispatch:
    inputs:
      version:
       required: false
       description: "A version to install ecspresso"
       default: "v1.3.2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.version }}
      - run: |
          if [ ${{ github.event.inputs.version }} = "latest" ]; then
            FILENAME=$(curl -sS https://api.github.com/repos/kayac/ecspresso/releases/latest|jq -r '.assets[].name|select(test("linux-amd64.zip"))')
          else
            FILENAME=ecspresso-${{ github.event.inputs.version }}-linux-amd64
          fi
          cd /tmp
          curl -sLO https://github.com/kayac/ecspresso/releases/download/${{ github.event.inputs.version }}/${FILENAME}.zip
          unzip ${FILENAME}.zip
          sudo install ${FILENAME} /usr/local/bin/ecspresso
          rm -f ${FILENAME} ${FILENAME}.zip
